### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by cooperq**
install with sudo so that the binary is actually in the path. 
add api key generation instructions.

### CODE REVIEW

**Comment by botherder** [comment]
I wish they'd put $HOME/.local/bin in $PATH by default :(

**Comment by cooperq** [comment]
Is *THAT* where all the binaries installed by pip go? I had no idea!  Would you rather I modify this to suggest adding that to the $PATH than installing as sudo?

**Comment by botherder** [comment]
Good question. I'm actually not sure what's best practice. Typically I install locally rather than globally, but that's just my personal preference.

**Comment by cooperq** [comment]
well since this is the admin console running on someones possibly managed laptop it's probably best not to have to invoke root privileges to run it, I'll modify to include instructions for adding the path. Any other blockers to accepting this PR?

**Comment by botherder** [comment]
Nope, sounds good. Thanks :+1:

**Pull request merged**
